version: "3.8"

services:
  nexus:
    image: sonatype/nexus3:3.63.0
    env_file:
      - .env
    volumes:
      - ../data/${COMPOSE_PROJECT_NAME}/nexus-data:/nexus-data
    ports:
      - "8081:8081"
networks:
  default:
    external:
      name: infra_network
