# docker compose 6 node redis cluster
version: "3.8"
services:
  redis1:
    image: redis:7.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis1.conf:/usr/local/etc/redis/redis.conf
  redis2:
    image: redis:7.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis2.conf:/usr/local/etc/redis/redis.conf
  redis3:
    image: redis:7.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis3.conf:/usr/local/etc/redis/redis.conf
  redis4:
    image: redis:7.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis4.conf:/usr/local/etc/redis/redis.conf
  redis5:
    image: redis:7.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis5.conf:/usr/local/etc/redis/redis.conf
  redis6:
    image: redis:7.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis6.conf:/usr/local/etc/redis/redis.conf
networks:
  default:
    external:
      name: infra_network