apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  serviceAccountName: og-admin
  containers:
    - name: example-container
      image: nginx
      resources:
        limits:
          cpu: "0.2"
          memory: "50M"
