# nacos docker compose file
version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos
    restart: always
    ports:
      - 8848:8848
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql-nas
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=${MYSQL_ROOT_PASSWORD}
networks:
  default:
    external:
      name: infra_network