# nacos docker compose file
version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos
    env_file:
      - .env
    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
networks:
  default:
    external:
      name: infra_network
