# mysql 8.0
version: '3.8'
services:
  mysql-nas:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env.default
      - .env
    volumes:
      - ../data/${COMPOSE_PROJECT_NAME}/mysql-data:/var/lib/mysql
networks:
  default:
    external:
      name: infra_network