version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    pull_policy: never
    env_file:
      - .env.default
      - .env
    ports:
      - 5432:5432
    volumes:
      - ../data/${COMPOSE_PROJECT_NAME}/postgres-data:/var/lib/postgresql/data