version: "3.8"
services:
  postgres:
    image: postgres:15.5
    restart: always
    pull_policy: never
    env_file:
      - .env.default
      - .env
    ports:
      - 5433:5432
    volumes:
      - ../data/${COMPOSE_PROJECT_NAME}/postgres-data:/var/lib/postgresql/data
networks:
  default:
    external:
      name: infra_network